# Generated by Django 4.2.7 on 2025-11-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='instant_booking',
            field=models.BooleanField(default=False, help_text='Allow students to instantly book without approval'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages taught', max_length=255),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='total_hours_taught',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours taught across all students', max_digits=10),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('can_approve_tutors', models.BooleanField(default=True)),
                ('can_manage_payments', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
            },
        ),
    ]
