# Generated by Django 4.2.7 on 2025-11-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_trial_lesson',
            field=models.BooleanField(default=False, help_text='First lesson with this tutor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('1_per_week', '1 Lesson per Week'), ('2_per_week', '2 Lessons per Week'), ('3_per_week', '3 Lessons per Week')], default='1_per_week', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('price_per_lesson', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lessons_per_billing_cycle', models.IntegerField(default=4, help_text='Number of lessons in 28-day cycle')),
                ('unused_lessons', models.IntegerField(default=0, help_text='Carry-over lessons from previous cycle')),
                ('renewal_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=False, help_text="Is this the student's first lesson with this tutor?")),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(blank=True, choices=[('student', 'Student'), ('tutor', 'Tutor'), ('auto', 'Automatic')], max_length=20, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True, help_text='Lesson notes from tutor')),
                ('homework', models.TextField(blank=True, help_text='Homework assigned to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Tutoring Lesson',
                'verbose_name_plural': 'Tutoring Lessons',
                'db_table': 'tutoring_lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_session_link', models.URLField(blank=True, help_text='Link to video call session', null=True)),
                ('whiteboard_notes', models.TextField(blank=True, help_text='Notes from whiteboard')),
                ('shared_files', models.JSONField(blank=True, default=list, help_text='List of file URLs shared during lesson')),
                ('recording_url', models.URLField(blank=True, help_text='Lesson recording URL', null=True)),
                ('session_started_at', models.DateTimeField(blank=True, null=True)),
                ('session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='bookings.lesson')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='If this booking is part of a subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('student', 'tutor'), name='unique_active_subscription_per_tutor'),
        ),
    ]
